[opener]
edit = [
	{ run = 'nvim %*',    block = true, desc = "nvim",           for = "windows" },
	{ run = 'nvim -w %*', block = true,  desc = "nvim (block)",   for = "windows" },
]
open = [
	{ run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
]
reveal = [
	{ run = 'explorer /select,"%1"', orphan = true, desc = "Reveal", for = "windows" },
]
extract = [
	{ run = 'ya pub extract --list %*',   desc = "Extract here", for = "windows" },
]
play = [
	{ run = 'mpv --force-window %*', orphan = true, for = "windows" },
]